### ISSUE TITLE
Daily frequency rules

### ISSUE THREAD

**Issue by ldmado** [AdobeDocs/journey-optimizer.it-IT#1]
Issue in ./help/using/configuration/frequency-rules.md

The DAILY frequency rules doesn't seems correctly documented. 

In January release notes there is the addition of the daily frequency cap: https://experienceleague.adobe.com/docs/journey-optimizer/using/whats-new/release-notes.html?lang=en#jan24-improvements
However, in the english documentation there is no reference to it (just weekly and monthly): https://experienceleague.adobe.com/docs/journey-optimizer/using/configuration/frequency-rules.html?lang=en#create-new-rule.
The Italian documentation is including a note on the daily cap (mixing italian and english words) which suggests using streaming segmentation instead of batch: https://experienceleague.adobe.com/docs/journey-optimizer/using/configuration/frequency-rules.html?lang=it#create-new-rule
Is this note right? Does it mean that the daily cap is not guaranteed for read-batch-audience journeys?

**Comment by Roberta-A** [comment]
@Idmado Thank you for your feedback, we are currently looking into this

**Comment by Roberta-A** [comment]
@ldmado Please note that this issue should now be resolved.
The page has been updated with information about daily cap (https://experienceleague.adobe.com/it/docs/journey-optimizer/using/configuration/frequency-rules#daily-frequency-cap)
